language: python
python:
- '3.5'
- '3.6'
- pypy
- pypy3
install:
- pip install .
- pip install -r requirements.txt
script: pytest
deploy:
  provider: heroku
  api_key:
    secure: eQkvaWEaKYX91ypH2iUr1kASTpe1M72jG/4m0ggxwTmVl+MiSFhz1vFcmkwpV7vQZJ/CxtfyoFJCwfIrqTiV9DRHJoGmqgcdsQ339yecPm4bkm9/hbS6cP9CvFiCVpkojIz7L/5nIf392dAJS2oRuPVoL/F3cFn1w6Zapq2LAmNSBINjpYbV1k8ACT+rXY1Jk7H6g4zAF+I2QmKDDSA3xqUDVPDVdyYoS63kbiO8ZHUDeta9+y0S4lHIlPIuh3od4I4MTmGJ9/9w4Nhz4i56VSIrpH/any1zp3o9IY9bz36tFa33+Kn0GyWph4nK6lb8Q84Oq3sP+APX4QysRh8/itNriPY4SLDGLQsulOmY5jFq7saLwGwptAPK05eWFQvYTsvHF/FvuxcpZC4vcEauYoDkxiHr0SFowiRj/n5/nSYE7sbWSBcF3IIV18iy0eiFMokN8jrW9Wbj4zgvajbg/qyPHLy6zmYb+1L+uUK8r3jo2Zedw02TWjV5jTCn8yxzwspHZplU4dbOqpVMhgCcj2ufdpTy7qW5p1p16pLljjzVQ9egAEycavTr++LUEGFtaXtlPpgWDjGMNrFvXykHh+xWyaKPHwBb2Zjal8TvIdh3F1Jsbnq6EkLwpQUuc/Sc+zuihVW/aAgWj5OyCRAJyOucSiChfu3B6uGOXJZxjYA=
  app: freightor
  on:
    repo: freightor/freightor
